[pytest]
# pytest - directory where tests are located
testpaths = tests

# pytest - verbose output
# addopts = -v

# pytest - file patterns to identify test files
# python_files = test_*.py *_test.py

#python_files = *_spec.py
#python_functions = should_*
#python_classes = Spec*
#
#addopts = -ra -q
#addopts = --tb=short
#addopts = --maxfail=2
#addopts = --disable-warnings
#