import re
from playwright.sync_api import Playwright, sync_playwright, expect
import time

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()

    page.goto("https://eta.onlineservices-servicesenligne-ste.apps.cic.gc.ca/eta/welcome?lang=en")
    time.
    expect(page).to_have_title("eService - Immigration, Refugees and Citizenship Canada")

    page.get_by_label("Are you applying on behalf of").select_option("1")
    page.get_by_role("button", name="Next").click()

    page.get_by_label("What travel document do you").select_option("0")
    page.get_by_label("Select the code that matches").select_option("64")
    page.get_by_label("What is the nationality noted").select_option("62")
    page.get_by_role("textbox", name="* Passport number (required)").click()
    page.get_by_role("textbox", name="* Passport number (required)").fill("ABC123")
    page.get_by_role("textbox", name="* Passport number (required)").press("Tab")
    page.get_by_role("textbox", name="* Passport number (re-enter").fill("ABC123")
    page.get_by_role("textbox", name="* Passport number (re-enter").press("Tab")
    page.get_by_role("button", name=" Help - Surname(s) / last").press("Tab")
    page.get_by_role("textbox", name="* Surname(s) / last name(s) (").fill("Adnane")
    page.get_by_role("textbox", name="* Surname(s) / last name(s) (").press("Tab")
    page.get_by_role("textbox", name="Given name(s) / first name(s)").fill("Stitou")
    page.get_by_role("textbox", name="Given name(s) / first name(s)").press("Tab")
    page.get_by_label("Date of birth - Year (").select_option("39")
    page.get_by_label("Date of birth - Month (").select_option("0")
    page.get_by_label("Date of birth - Day (required)").select_option("0")
    page.get_by_label("Gender (required)").select_option("1")
    page.get_by_label("Country/territory of birth (").select_option("75")
    page.get_by_role("textbox", name="* City/town of birth (").click()
    page.get_by_role("textbox", name="* City/town of birth (").fill("Paris")
    page.get_by_label("Issue date - Year (required)").select_option("14")
    page.get_by_label("Issue date - Month (required)").select_option("0")
    page.get_by_label("Issue date - Day (required)").select_option("0")
    page.get_by_label("Expiry date - Year (required)").select_option("3")
    page.get_by_label("Expiry date - Month (required)").select_option("0")
    page.get_by_label("Expiry date - Day (required)").select_option("0")
    page.get_by_label("Additional nationalities -").select_option("59")
    page.get_by_label("Marital status (required)").select_option("6")
    page.get_by_label("Have you ever applied for or").select_option("1")
    page.get_by_label("Occupation (required)").select_option("12")
    page.get_by_role("textbox", name="* Name of employer or school").click()
    page.get_by_role("textbox", name="* Name of employer or school").fill("Ecole des Arts, Paris")
    page.get_by_role("group", name="Employment information").get_by_label("Country/territory (required)").select_option("74")
    page.get_by_role("group", name="Employment information").get_by_label("City/town (required)").click()
    page.get_by_role("group", name="Employment information").get_by_label("City/town (required)").fill("Paris")
    page.get_by_role("group", name="* Since what year? (required)").get_by_label("Since what year? (required)").select_option("0")
    page.get_by_label("Preferred language to contact").select_option("1")
    page.get_by_role("textbox", name="* Email address (required)").click()
    page.get_by_role("textbox", name="* Email address (required)").fill("adnane.stitou@cic.gc.ca")
    page.get_by_role("textbox", name="* Email address (required)").press("Tab")
    page.get_by_role("textbox", name="* Email address (re-enter) (").fill("adnane.stitou@cic.gc.ca")
    page.get_by_role("textbox", name="* Email address (re-enter) (").press("Tab")
    page.get_by_role("textbox", name="Apartment/unit number (if").fill("123")
    page.get_by_role("textbox", name="Apartment/unit number (if").press("Tab")
    page.get_by_role("textbox", name="* Street/civic number or").fill("Main St")
    page.get_by_role("textbox", name="* Street/civic number or").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="* Street/civic number or").fill("345")
    page.get_by_role("textbox", name="* Street/civic number or").press("Tab")
    page.get_by_role("textbox", name="* Street address/name (").fill("Main Street")
    page.get_by_role("textbox", name="* Street address/name (").press("Tab")
    page.get_by_role("textbox", name="Street address/name line 2 (").press("Tab")
    page.get_by_role("group", name="Residential address Enter").get_by_label("City/town (required)").fill("Paris")
    page.get_by_role("group", name="Residential address Enter").get_by_label("City/town (required)").press("Tab")
    page.get_by_role("group", name="Residential address Enter").get_by_label("Country/territory (required)").select_option("74")
    page.get_by_label("Do you know when you will").select_option("0")
    page.get_by_label("Travel to Canada - Year (").select_option("0")
    page.get_by_label("Travel to Canada - Month (").select_option("6")
    page.get_by_label("Travel to Canada - Day (").select_option("0")
    page.get_by_label("Travel to Canada - Hour (").select_option("9")
    page.get_by_label("Travel to Canada - Minute (").select_option("10")
    page.get_by_label("Travel to Canada - Time zone").select_option("52")
    page.get_by_label("Have you ever been refused a").select_option("1")
    page.get_by_label("Have you ever committed, been").select_option("1")
    page.get_by_label("In the past two years, were").select_option("1")
    page.get_by_label("Do you have one of these").select_option("3")
    page.get_by_role("checkbox", name="I Agree").check()
    page.get_by_role("textbox", name="* Signature of applicant (").click()
    page.get_by_role("textbox", name="* Signature of applicant (").fill("Adnane Stitou")
    page.get_by_role("button", name="Proceed to Payment").click()
    page.get_by_role("button", name="Transmit and pay").click()
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Email").click()
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Email").fill("adnane.stitou@cic.gc.ca")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Email").press("Tab")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Phone Number").fill("819 555-5555")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Cardholder Name").click()
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Cardholder Name").fill("JOAN SMITH")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Cardholder Name").press("Tab")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Card Number").fill("5204740000000525")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Card Number").press("Tab")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Expiry Date MMYY").fill("1")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Expiry Date MMYY").click()
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Expiry Date MMYY").fill("1125")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Expiry Date MMYY").press("Tab")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("button", name="CVV - Card Verification Value").press("Tab")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="CVV").fill("1122")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="CVV").press("Tab")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Address Line 1").fill("35 Main St")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Address Line 1").press("Tab")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Address Line 2 (optional)").press("Tab")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="City").fill("Ottawa")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="City").press("Tab")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_label("Country").press("Tab")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_label("Province or State").select_option("ON")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_label("Province or State").press("Tab")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Postal or ZIP Code").fill("J9J0B3")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("button", name="Checkout").click()
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Expiry Date MMYY").click()
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("textbox", name="Expiry Date MMYY").fill("1126")
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("button", name="Checkout").click()
    page.locator("iframe[title=\"Payment Details\"]").content_frame.get_by_role("button", name="Back").click()
    page.get_by_role("button", name="Transmit and pay").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
